# Generated by Django 2.2.10 on 2025-01-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20210410_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '前台用户', 'verbose_name_plural': '前台用户'},
        ),
    ]
